### ISSUE TITLE
domain must be a non empty string

### ISSUE THREAD

**Issue by SeriousM** [keesschollaart81/AzureCostInsights.Marketplace#31]
Hi! When running the download task with an MSDN Abo Subscription where we get 150 euro every month the task fails with the message `domain must be a non empty string`.
The offerid is `MS-AZR-0063P` and the error occurs with usage and consumption api.
In contrast the Visual Studio Enterprise subscription works without any flaws.

Is there anything I can help you with except the log?
Thanks, B.

```log
2020-08-12T09:07:33.7726070Z ##[section]Starting: Download cost data: xxxx
2020-08-12T09:07:33.7739355Z ==============================================================================
2020-08-12T09:07:33.7739748Z Task         : Download Cost Data
2020-08-12T09:07:33.7740699Z Description  : Fetch your Azure Cost data and prepare it for use in the widget
2020-08-12T09:07:33.7741080Z Version      : 1.0.30
2020-08-12T09:07:33.7741359Z Author       : Kees Schollaart
2020-08-12T09:07:33.7741823Z Help         : [More Information](https://github.com/keesschollaart81/CaseOnline.AzureCostInsights)
2020-08-12T09:07:33.7742339Z ==============================================================================
2020-08-12T09:07:34.3732619Z Logging in using ApplicationTokenCredentials, authScheme is 'ServicePrincipal'
2020-08-12T09:07:34.3751948Z Unhandled exception during Download Task Error: domain must be a non empty string.
2020-08-12T09:07:34.3753021Z     at new <anonymous> (/home/vsts/work/_tasks/DownloadCostData_adff96fa-a978-4c69-8fb4-08fda81b3c15/1.0.30/index.js:3:247358)
2020-08-12T09:07:34.3754375Z     at u.getCredentials (/home/vsts/work/_tasks/DownloadCostData_adff96fa-a978-4c69-8fb4-08fda81b3c15/1.0.30/index.js:129:79751)
2020-08-12T09:07:34.3755386Z     at u.<anonymous> (/home/vsts/work/_tasks/DownloadCostData_adff96fa-a978-4c69-8fb4-08fda81b3c15/1.0.30/index.js:129:78154)
2020-08-12T09:07:34.3755799Z     at next (native)
2020-08-12T09:07:34.3756589Z     at /home/vsts/work/_tasks/DownloadCostData_adff96fa-a978-4c69-8fb4-08fda81b3c15/1.0.30/index.js:129:77818
2020-08-12T09:07:34.3757503Z     at n (/home/vsts/work/_tasks/DownloadCostData_adff96fa-a978-4c69-8fb4-08fda81b3c15/1.0.30/index.js:129:77592)
2020-08-12T09:07:34.3758683Z     at u.run (/home/vsts/work/_tasks/DownloadCostData_adff96fa-a978-4c69-8fb4-08fda81b3c15/1.0.30/index.js:129:77954)
2020-08-12T09:07:34.3759710Z     at Object.defineProperty.value (/home/vsts/work/_tasks/DownloadCostData_adff96fa-a978-4c69-8fb4-08fda81b3c15/1.0.30/index.js:129:80040)
2020-08-12T09:07:34.3761153Z     at r (/home/vsts/work/_tasks/DownloadCostData_adff96fa-a978-4c69-8fb4-08fda81b3c15/1.0.30/index.js:1:400)
2020-08-12T09:07:34.3761972Z     at /home/vsts/work/_tasks/DownloadCostData_adff96fa-a978-4c69-8fb4-08fda81b3c15/1.0.30/index.js:1:1199
2020-08-12T09:07:34.3843702Z ##[error]Error: domain must be a non empty string.
2020-08-12T09:07:34.7432198Z ##[section]Finishing: Download cost data: xxxx

```

**Comment by jlavoy** [comment]
Seeing the same thing for offerid MS-AZR-0003P and 0136P

**Comment by boopathigithub** [comment]
@SeriousM Issue resolved? I am getting similar issue but with different error

**Comment by pinarodrigo** [comment]
@SeriousM Same issue here, any updates?

**Comment by erikumhoefer** [comment]
I am also experiencing this issue on multiple subscriptions with various offer IDs.

**Comment by crazycga** [comment]
I'm surprised this is still an issue.  Is there any resolution to this one?

**Comment by AlvaroGCachon** [comment]
Same issue here, enabling debug mode does not provide additional information.
